# Generated by Django 2.2.17 on 2021-03-15 22:53

from django.db import migrations, models
import django.db.models.deletion
import forum.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryName', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('userName', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hack',
            fields=[
                ('hackID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('shortDescription', models.CharField(max_length=55)),
                ('likes', models.IntegerField(default=0)),
                ('dateTimeCreated', models.DateTimeField()),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Category')),
                ('userName', models.ForeignKey(on_delete=models.SET(forum.models.getNoUsernameText), to='forum.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('dateTimeCreated', models.DateTimeField()),
                ('hackID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Hack')),
                ('userName', models.ForeignKey(on_delete=models.SET(forum.models.getNoUsernameText), to='forum.UserAccount')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='userName',
            field=models.ForeignKey(on_delete=models.SET(forum.models.getNoUsernameText), to='forum.UserAccount'),
        ),
    ]
