# Generated by Django 2.2.17 on 2021-03-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='achange',
            field=models.BooleanField(default=False),
        ),
    ]
