# Generated by Django 2.2.17 on 2021-03-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hack',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
