# Generated by Django 2.2.17 on 2021-03-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_useraccount_achange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='achange',
        ),
    ]
