# Generated by Django 2.2.17 on 2021-03-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210329_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hack',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
